### ISSUE TITLE
[telegram]: Add /stop command to stop the telegram bot

### ISSUE THREAD

**Issue by alexbosworth** [alexbosworth/balanceofsatoshis#199]
Add a new command /stop which will kill the running bot

**Comment by niteshbalusu11** [comment]
I think we have to switch all request methods to grammy to get this to work. Right now adding a /stop command and doing a `await bot.stop()` works only in stopping all commands but it fails to stop subscriptions because they are using request to send notifications.

**Comment by alexbosworth** [comment]
How about stop = `process.kill()`

**Comment by niteshbalusu11** [comment]
Yeah, I think that would work. How do we get the PID for the current process?

Although switching from request to grammy won't take long I think. Do you think it's a good idea to wait and do this after the switch? I opened a PR for 3 methods to start with.

**Comment by alexbosworth** [comment]
`process.kill()` with no arguments should just exit the running process

I can take a look at the telegram pr

**Comment by niteshbalusu11** [comment]
Just like this? It's throwing an error.

```
        bot.command('stop', async ctx => {
          try {
            await ctx.reply(interaction.stop_bot, markdown);
            process.kill();
          } catch (err) {
            logger.error({err});
          }
        });
```

```
err: 
  message: The "pid" argument must be of type number. Received undefined
  stack: 
    - TypeError [ERR_INVALID_ARG_TYPE]: The "pid" argument must be of type number. Received undefined
```
