### ISSUE TITLE
open-balanced-channel fails with "UnknownPaymentHash"

### ISSUE THREAD

**Issue by pvorangecrush** [alexbosworth/balanceofsatoshis#496]
I can connect to other node and initiate open-balanced-channel, but it keeps throwing **UnknownPaymentHash** error. Same was true when dual-funded channel was initiated by the other node. 

keysend and amp are enabled in LND.

```
? Public key of the node to request a balanced open with? XXXX

checking_route: 
  - 779803x2437x0 ★ ★ ★ ★
  - djmeistro 035b710d2c8d25993ddcbe031c0fee5434d5e6fb7a6ed5d438404daa99199537b8. Fee rate: 0.02% (200)
  - 779148x1691x1x1
? Total capacity of the new channel? 4000000
? Fee rate per vbyte for the joint funding transaction? 33
? Use internal wallet funds? Yes

refund_transaction: XXXX
finding_route: 
  - 779803x2437x0 ★ ★ ★ ★
  - djmeistro 035b710d2c8d25993ddcbe031c0fee5434d5e6fb7a6ed5d438404daa99199537b8. Fee rate: 0.02% (200)
  - 779148x1691x1x1

requesting_balanced_open_channel: true

err: 
  - 404
  - UnknownPaymentHash
  - 
    failures: 
      - 
        - 404
        - UnknownPaymentHash
        - 
          height: 779946
          index:  2
          policy: null
```
